### ISSUE TITLE
ERROR in The target entry-point "apollo-angular" has missing dependencies:  - @apollo/client/core

### ISSUE THREAD

**Issue by ealejandromt** [kamilkisiela/apollo-angular#1538]
**Describe the bug**

Just updated to new version and brings the error after build:

ERROR in The target entry-point "apollo-angular" has missing dependencies:
 - @apollo/client/core

**To Reproduce**

Install last version (2.0.2) and try to build it

**Expected behavior**

It should build the application

**Environment:**

- `apollo-angular`:

**Comment by kamilkisiela** [comment]
Works for me. 

Could you share your `package.json` or at least versions of `@angular/core`, `@angular/cli` and `@apollo/client`?

**Comment by phani17c** [comment]
I too having the similar issue
Here are my versions:
"@angular/core": "10.0.8",
 "apollo-angular": "2.0.3",
 "@angular/cli": "10.0.5",

**Comment by kugelvlitz** [comment]
I had a very similar issue and spent way too much time looking for a fix. Turns out the latest Angular release doesn't play well with Apollo. I had to revert to Angular 9.1.10 for it to work.

**Comment by kamilkisiela** [comment]
@kugelvlitz @phani17c could you share a minimal reproduction, something I could take a look at? I can't guess what's your angular-cli.json looks like or package.json or tsconfig etc

**Comment by phani17c** [comment]
My issue got fixed with adding apollo-graphql 0.5.0v in my package.json explicitly.

**Comment by kamilkisiela** [comment]
@phani17c I'm not sure it's the solution, there is something either to fix in angular or apollo. Installing a package doesn't seem like a right workaround.

**Comment by danielehrhardt** [comment]
i have the same Issue

**Comment by sarora2073** [comment]
Same issue here, and above steps from @danielehrhardt didn't resolve it for me. I do notice that ApolloModule is no longer a valid export, as shown in the attached. I was previously importing both ApolloModule and Apollo from apollo-angular. Any ideas?

![2020-08-12_11-50-27](https://user-images.githubusercontent.com/8941430/90037683-7b49ee00-dc92-11ea-9cea-28a71028c84a.png)

**Comment by kamilkisiela** [comment]
@sarora2073 please take a look at https://apollo-angular.com/docs/migration/#no-ngmodules

**Comment by sarora2073** [comment]
@kamilkisiela Thanks for that! Went through all the changes in detail (removing http-link packages, and apollo-cache-inmemory), changed code to import from graphql-tag from apollo-angular etc. etc. Unfortunately still getting that same pesky error. 

This started when I installed the latest apollo-client 2.6.10  while i was upgrading from ng9 to ng10.  I notice now that the InMemoryCache import also fails for similar reasons... typescript doesn't recognize the @apollo/client/core package as shown in screenshot. Was there a new @types package for apollo-angular release? Or maybe this is a bug?

![image](https://user-images.githubusercontent.com/8941430/90040793-62433c00-dc96-11ea-8294-fb7c36bd6d3c.png)

**Comment by kamilkisiela** [comment]
@sarora2073 do you have `@apollo/client` package installed?

**Comment by sarora2073** [comment]
Sorry just realized that was the issue. Previous docs suggest that was only for react, so i got convinced i needed to still use apollo-angular, but now i get it! i've migrated to @apollo/client. New error.. have to figure out where to import IntrospectionFragmentMatcher :-(

**Comment by kamilkisiela** [comment]
I asked for a reproduction or some clues, no answers so I'm closing this one.

**Comment by sarora2073** [comment]
if you're using apollo-client (which apparently you are in the package.json above) you're going to run into the same issues  I did, which were asked and addressed above. You have to install  @apollo/client (new package) and read the migration guide above.
